add editor
tiger0421/waypoint_nav pull request #5
Opened 2021-07-29 11:28 UTC by taishiyamamoto

ウェイポイントの編集機能を追加
rvizのパネルの追加

コマンド
```
#Editor
roslaunch waypoint_nav editor.launch 

#Run
roslaunch waypoint_nav run.launch 
```

2021-07-29 15:40 UTC, tiger0421 commented on launch/editor.launch
> +
map_serverを一緒に起動してくれると親切だと思います．

2021-07-29 15:40 UTC, tiger0421 commented on config/function_list.yaml
> +function_list: [run,suspend,hoge]
このファイルは何ですか？

2021-07-29 15:42 UTC, tiger0421 commented on launch/run.launch
> +    <param name="robot_frame" value="base_footprint"/>
orneにそのまま適応するためにもbase_footprintではなくbase_linkの方を使いたいです．

2021-07-29 15:46 UTC, tiger0421 commented on rviz/editor.rviz
> +Panels:
もしeditor.launchにmap_serverを追加するならこっちにも反映をお願いします．

2021-07-29 15:51 UTC, tiger0421 commented on src/save_trigger_panel.h
> +#ifndef SAVE_TRIGGER_PANEL_H
include ディレクトリを作ってその中に入れて欲しいです．

2021-07-29 15:54 UTC, tiger0421 requested changes
Thank you

2021-07-29 15:54 UTC, tiger0421 commented on src/state_trigger_panel.h
> +#ifndef STATE_TRIGGER_PANEL_H
include ディレクトリを作ってその中に入れて欲しいです．

2021-07-30 02:10 UTC, tiger0421 requested changes
function_list.yamlは理解しました．

2021-07-30 08:30 UTC, taishiyamamoto reviewed
修正しました。

2021-07-30 09:11 UTC, tiger0421 approved these changes
Thank you for your PR

2021-07-30 09:11 UTC, merged